apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otel-collector
resources:
  - ../../base
configMapGenerator:
  - name: otel-cluster-facts
    behavior: create
    literals:
      - cluster=gcp-secondary
      - remoteWriteEndpoint=http://prometheus-server.prometheus.svc.cluster.local/api/v1/write
generatorOptions:
  disableNameSuffixHash: true
