#!/usr/bin/env bash
#
# The SLO evaluator, running OUTSIDE both clusters.
#
# It used to live in gcp-secondary. ADR 0005 moved the *probe* out of the
# clusters after the first game day proved an in-cluster prober cannot see its
# own cluster die; this moves the thing that *reads* the probe out as well, for
# the same reason. A prober that survives either cloud is worth little if the
# evaluator reading it dies with one of them — losing gcp-secondary lost the
# SLO, which is precisely the failover the SLO exists to measure.
#
# This is the local stand-in for the backend ADR 0002 plans to reach at burst
# time (Grafana Cloud). Same siting, same property: outside both clouds, so a
# failover lands somewhere the measurements are still readable.
#
# CONSEQUENCE, ACCEPTED: the evaluator is no longer GitOps-managed, because it
# is no longer in a cluster for Argo to manage. The rules it runs are still
# committed — `make slo` writes slo/rules/dr.rules.yaml and this script copies
# exactly those files in — so "the rules a reviewer reads in a PR are the rules
# that actually run" still holds. Only the delivery mechanism changed.
#
# It also removes a hack. In-cluster, the rules ConfigMap needed a hash suffix
# to force a pod roll, because Prometheus reads rule files at startup and does
# not watch them. Here `reload` POSTs to /-/reload, which is what that hash was
# imitating.
#
#   ./scripts/evaluator.sh up
#   ./scripts/evaluator.sh status
#   ./scripts/evaluator.sh reload      # after `make slo`
#   ./scripts/evaluator.sh down        # keeps the TSDB volume
#   ./scripts/evaluator.sh destroy     # drops the TSDB volume too
#
set -euo pipefail
cd "$(dirname "$0")/.."

NETWORK="${INTERCONNECT:-dr-interconnect}"
CONTAINER="${EVAL_CONTAINER:-dr-evaluator}"
IMAGE="${EVAL_IMAGE:-prom/prometheus:v3.14.0}"
VOLUME="${EVAL_VOLUME:-dr-evaluator-data}"
EVAL_ADDR="${EVAL_ADDR:-172.30.0.40}"
EVAL_PORT="${EVAL_PORT:-19090}"
PROBER_ADDR="${TM_ADDR:-172.30.0.30}:${TM_METRICS_PORT:-9101}"
URL="http://127.0.0.1:${EVAL_PORT}"

BOLD=$'\033[1m'; DIM=$'\033[2m'; RED=$'\033[0;31m'; GREEN=$'\033[0;32m'; YEL=$'\033[0;33m'; OFF=$'\033[0m'

# Two small readers, written out rather than inlined. Inlining them meant a
# python -c string inside a bash function inside a quoted heredoc, and the
# quoting broke silently — status printed a SyntaxError where the numbers go.
RULE_COUNTER="$(mktemp)"; TARGET_LISTER="$(mktemp)"
trap 'rm -f "$RULE_COUNTER" "$TARGET_LISTER"' EXIT

cat > "$RULE_COUNTER" <<'PYEOF'
import json, sys
try:
    groups = json.load(sys.stdin)["data"]["groups"]
except Exception:
    print("?")
    raise SystemExit
n = sum(len(g["rules"]) for g in groups)
print("%d in %d group(s)" % (n, len(groups)))
PYEOF

cat > "$TARGET_LISTER" <<'PYEOF'
import json, sys
GRN, RED, OFF = "\033[0;32m", "\033[0;31m", "\033[0m"
try:
    targets = json.load(sys.stdin)["data"]["activeTargets"]
except Exception:
    targets = []
for x in sorted(targets, key=lambda i: i["labels"].get("job", "")):
    job = x["labels"].get("job", "?")
    health = x["health"]
    colour = GRN if health == "up" else RED
    print("  %-30s %s%s%s  %s" % (job, colour, health, OFF, x["scrapeUrl"]))
PYEOF

write_config() {
  cat <<EOF
# Generated by scripts/evaluator.sh. The evaluator runs outside both clusters,
# so its scrape targets are environment facts and belong here rather than in a
# kustomize base — the same split that kept substrate addresses out of the app
# manifests when this lived in the cluster.
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yaml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  # The outside-in prober. SCRAPED, not pushed: a target that stops answering
  # gets up == 0 written immediately, and the availability SLI is built on that
  # distinction. A pushing source produces no liveness signal at all.
  - job_name: dr-edge
    scrape_interval: 10s
    static_configs:
      - targets: ["${PROBER_ADDR}"]
        labels:
          probe_origin: external
EOF
}

install_files() { # install_files <target-container-state>
  local tmp; tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' RETURN
  mkdir -p "$tmp/rules"
  write_config > "$tmp/prometheus.yml"
  cp slo/rules/*.yaml "$tmp/rules/"
  docker cp "$tmp/." "${CONTAINER}:/etc/prometheus/" >/dev/null
}

cmd_up() {
  docker network inspect "$NETWORK" >/dev/null 2>&1 || {
    echo "interconnect network '$NETWORK' missing — run make up first" >&2; exit 1; }
  compgen -G "slo/rules/*.yaml" >/dev/null || {
    echo "no rules in slo/rules — run make slo first" >&2; exit 1; }

  docker volume inspect "$VOLUME" >/dev/null 2>&1 || {
    printf '%s==> creating TSDB volume %s%s\n' "$BOLD" "$VOLUME" "$OFF"
    docker volume create "$VOLUME" >/dev/null
  }
  # A fresh named volume is root-owned and the image runs as nobody, so
  # Prometheus would fail to open its TSDB. One-off, and idempotent.
  docker run --rm -v "${VOLUME}:/prometheus" alpine:3.20 \
    chown -R 65534:65534 /prometheus >/dev/null 2>&1

  printf '\n%s==> starting the evaluator outside both clusters%s\n' "$BOLD" "$OFF"
  docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
  # create + cp + start, rather than starting on a stock config and correcting
  # it: docker cp works on a created container, so the evaluator never runs a
  # config we did not write.
  docker create --name "$CONTAINER" \
    --network "$NETWORK" --ip "$EVAL_ADDR" \
    -p "${EVAL_PORT}:9090" \
    -v "${VOLUME}:/prometheus" \
    --memory 512m \
    "$IMAGE" \
      --config.file=/etc/prometheus/prometheus.yml \
      --storage.tsdb.path=/prometheus \
      --storage.tsdb.retention.time=24h \
      --web.enable-remote-write-receiver \
      --web.enable-lifecycle >/dev/null
  install_files
  docker start "$CONTAINER" >/dev/null

  for _ in $(seq 1 60); do
    curl -sf --max-time 2 "$URL/-/ready" >/dev/null 2>&1 && break
    sleep 1
  done
  cmd_status
}

cmd_reload() {
  docker inspect "$CONTAINER" >/dev/null 2>&1 || { echo "${DIM}evaluator not running — skipping reload${OFF}"; return 0; }
  install_files
  if curl -sf --max-time 5 -X POST "$URL/-/reload" >/dev/null; then
    printf '  %sreloaded%s rules into the running evaluator\n' "$GREEN" "$OFF"
  else
    printf '  %sreload failed%s — the evaluator is still running the OLD rules\n' "$RED" "$OFF" >&2
    return 1
  fi
}

cmd_down()    { docker rm -f "$CONTAINER" >/dev/null 2>&1 && echo "removed $CONTAINER (TSDB volume kept)" || echo "$CONTAINER not running"; }
cmd_destroy() { cmd_down; docker volume rm "$VOLUME" >/dev/null 2>&1 && echo "removed volume $VOLUME" || true; }

cmd_status() {
  if ! docker inspect "$CONTAINER" >/dev/null 2>&1; then
    printf '\n  %sevaluator not running%s — make evaluator\n\n' "$RED" "$OFF"; return 1
  fi
  printf '\n%s  SLO evaluator%s   %s%s (outside both clusters)%s\n\n' "$BOLD" "$OFF" "$DIM" "$URL" "$OFF"

  local ready; ready=$(curl -s --max-time 3 "$URL/-/ready" 2>/dev/null || true)
  if [[ "$ready" == *"Ready"* ]]; then
    printf '  %-18s %sready%s\n' "evaluator" "$GREEN" "$OFF"
  else
    printf '  %-18s %snot ready%s\n' "evaluator" "$RED" "$OFF"; return 1
  fi

  local rules
  rules=$(curl -s --max-time 3 "$URL/api/v1/rules" | python3 "$RULE_COUNTER" 2>/dev/null || echo '?')
  printf '  %-18s %s\n\n' "rules loaded" "$rules"

  printf '  %-30s %s\n' "TARGET" "STATE"
  curl -s --max-time 3 "$URL/api/v1/targets" | python3 "$TARGET_LISTER" 2>/dev/null || echo "  (targets unavailable)"
  echo
}

case "${1:-status}" in
  up)      cmd_up ;;
  status)  cmd_status ;;
  reload)  cmd_reload ;;
  down)    cmd_down ;;
  destroy) cmd_destroy ;;
  *) sed -n '/^#   \.\//,/^#$/p' "$0" | sed 's/^# \{0,1\}//' ; exit 2 ;;
esac
